### ISSUE TITLE
Bot lost sales log for a PAIR

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#1797] opened 2018-05-06 13:48 UTC
Here is my latest sales log from admin panel
<img width="1591" alt="2018-05-06 15 46 46" src="https://user-images.githubusercontent.com/5228422/39673918-cc5b6ed0-5144-11e8-8631-7deb5eeafb50.png">

No CMTETH

And here is log form bot 
2018-05-06 15:43:50 INFO StrategyRunnerHelper - SELLLOG: {"boughtTimes":1,"buyProfit":0.0,"lastOrderNumber":"10024380","unfilledAmount":0.0,"market":"CMTETH","profit":1.4179322874469105,"orderbookProfit":1.4203874199013147,"averageCalculator":{"totalCost":0.023623690000000003,"totalAmount":58.0,"totalAmountWithSold":0.0,"avgPrice":4.0730500000000006E-4,"avgCost":0.023623690000000003,"firstBoughtDate":{"date":{"year":2018,"month":5,"day":6},"time":{"hour":13,"minute":12,"second":18,"nano":944000000}},"totalWeightedPrice":0.023623690000000003,"orderNumber":0.0,"fee":0.2},"currentPrice":4.139E-4,"buyStrategies":[],"sellStrategies":[{"type":"SELL","name":"HIGHBB","entryValue":30.0,"entryValueLimit":0.0,"triggerValue":0.0,"currentValue":-16.621152608929805,"currentValuePercentage":0.0,"decimals":1,"positive":"true trailing..."},{"type":"SELL","name":"GAIN","entryValue":0.1,"entryValueLimit":0.0,"triggerValue":0.0,"currentValue":2.0268051361370887,"currentValuePercentage":0.0,"decimals":2,"positive":"true trailing..."},{"type":"SELL","name":"RSI","entryValue":50.0,"entryValueLimit":0.0,"triggerValue":0.0,"currentValue":62.14153544212086,"currentValuePercentage":0.0,"decimals":0,"positive":"true trailing..."}],"volume":10623.67529798,"percChange":-0.03172,"originalTrailingData":{"originalTrigger":0.0,"originalWidth":0.0,"originalValue":0.1,"lastTrailTime":{"date":{"year":2018,"month":5,"day":6},"time":{"hour":13,"minute":44,"second":44,"nano":818000000}}}}

PT 2.0.2

**Comment by Heartinhand** [comment] 2018-05-06 18:27
![pt error sales 2](https://user-images.githubusercontent.com/37930285/39676484-743e3452-5163-11e8-9f63-96bbc118d984.png)

**Comment by maah75** [comment] 2018-05-06 20:16
I hsve the same issue for ETC
also I have this hpen before for pairs with following command 
ETC_sell_only_mode_enabled = true
ETC_DCA_enabled = false
if the pairs in sell onle mode will not recored the sell prise log

**Comment by SgtBatten** [comment] 2018-05-06 21:35
Duplicate of #1720

**Comment by SgtBatten** [comment] 2018-05-06 21:36
@maah75 please add this information/theory to #1720

**Closed by SgtBatten** 2018-05-06 21:36 UTC
