### ISSUE TITLE
Average price (bought_cost) missing after new buy

### ISSUE THREAD

**Issue by vennechris** [taniman/profit-trailer#1860] opened 2018-05-14 14:18 UTC
as of v2.0.3 average price randomly missing on new positions.  Updated to v2.0.4 problem still not corrected.  Adding price via hotconfig will sell part of position, and forget the cost again.

NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dorianbanks** [comment] 2018-05-14 15:57
I am missing bought cost in my sells...assume this is the same error?

<img width="1256" alt="screen shot 2018-05-14 at 8 54 37 am" src="https://user-images.githubusercontent.com/37125619/40008695-c82f4b54-5754-11e8-8642-dc1e86ae3b82.png">

**Comment by vennechris** [comment] 2018-05-14 16:32
Yes, same error.  It is occurring after clearing dust, deleting logs, json, and backup, and restarting bot.  Hotconfig is not even working anymore

**Comment by alexdolli** [comment] 2018-05-14 19:49
Same problem here (Binance)

**Comment by kylanschilling** [comment] 2018-05-14 22:45
same here. 2.0.4 it started. binance

**Comment by CryptoKylan** [comment] 2018-05-14 22:51
i went back to 2.0.3 and it got the correct buy values again without having to fix it manually which was nice

**Comment by darkban** [comment] 2018-05-14 23:00
same the error... guys fix this problem... is impossible work whit this bot that lost price... this is a mega ug fix
![scher](https://user-images.githubusercontent.com/32014414/40027669-6327576a-57db-11e8-9f39-6129548716df.png)

**Comment by vennechris** [comment] 2018-05-14 23:07
Reverting to 2.0.3 does not fix it, the problem was present before update to 2.0.4

**Comment by CryptoKylan** [comment] 2018-05-14 23:27
well i was using 2.0.3 without issue. it was only until i updated it started and it went right back with .3 for me. seems ok now.  will wait and see

**Comment by learts13** [comment] 2018-05-15 01:46
same here. 2.0.4 it started. binance

**Comment by jcfii** [comment] 2018-05-15 07:53
Please fix hot config and incorrect average price problems in 2.0.4, problems started with 2.0.3

**Comment by VektorCRO** [comment] 2018-05-15 08:52
Any current fix for this problem?

**Comment by radawson** [comment] 2018-05-15 14:06
Same problem here - It happens both when buying pairs for the first time, and also when doubling down for DCA. This happened a few times with 2.0.3 and about 75% of the time with 2.0.4.

**Comment by LoukisD** [comment] 2018-05-15 14:15
Similar problem here, where my bot sell at a loss (confirmed from my Binance trade history) but in "sales log" it says that sell at 11.51% profit!! Also, in PT log file I have 2 EXPIRED orders for that pair and no FILLED orders, like it never bought the pair but 10' later it sold it.

**Comment by gh0st2017** [comment] 2018-05-16 01:38
same problems 2.0.5 watchmode paris

**Comment by HomeY** [comment] 2018-05-16 09:04
It also seems that the avg price is lost after a partial (panic) sale:
![image](https://user-images.githubusercontent.com/1996332/40107578-e6dc0786-58f8-11e8-9148-4f8a110f7554.png)
![image](https://user-images.githubusercontent.com/1996332/40107593-f57571a6-58f8-11e8-804f-d5003864b9aa.png)

**Comment by SgtBatten** [comment] 2018-05-16 09:27
@HomeY please add to the correctly related issue. and confirm the version you are on.
Issue you want is 1725

**Comment by vennechris** [comment] 2018-05-16 11:51
Issue is still present after 2.0.5 update. No change.

![screen shot 2018-05-16 at 6 48 57 am](https://user-images.githubusercontent.com/39270255/40115295-8f936b7c-58d5-11e8-9335-891bfa4f46ad.png)

**Comment by IAmNigh** [comment] 2018-05-16 16:54
Had the same issue this morning with QTUM, price set to zero after PT sells another coin. Missed the sale for QTUM because of this. Had nothing to do with manual buying or selling. Happened all within PT. Makes the product unusable. PLEASE FIX!

**Comment by helo03** [comment] 2018-05-17 11:06
@IAmNigh 
Can you please provide a log?
Especially after the "PT sells another coin".

Thank you,
Mario

**Comment by alexdolli** [comment] 2018-05-18 18:15
It's still happening in 2.0.6... :(
![image1](https://user-images.githubusercontent.com/36098310/40250974-f16e2946-5aa5-11e8-8a84-a84b4339de5f.png)

**Comment by alexdolli** [comment] 2018-05-18 23:10
I manually corrected it via HotConfig. I will try next time, if there actually is another time before 2.0.7. Looking forward to the new release!

**Closed** 2018-05-24 07:55 UTC
Labels: costing
