### ISSUE TITLE
TCV, SB, and Profit do not add up, Display value of USDT error

### ISSUE THREAD

**Issue by mygreeneggsandham** [taniman/profit-trailer#1685] opened 2018-04-27 17:41 UTC
The total current value is not the same as what Binance has. Also, adding the Profit Last Week total to the Starting Balance does not equal the Total Current Value. 
Also the Estimated Value for USDT displays ($NaN)
![image](https://user-images.githubusercontent.com/22647980/39376756-c648d4ae-4a20-11e8-9874-2e9e85b711ab.png)

**Comment by YoJeff** [comment] 2018-04-27 18:10
You running 3rd party addons?   Those are the cause of $NaN's the majority of the time.

**Comment by SgtBatten** [comment] 2018-04-27 21:55
Also start balance + profit last week will never = TCV unless all your pairs are at 0% loss/profit. So this is a non issue sorry. I'm going to close it.

**Closed by SgtBatten** 2018-04-27 21:55 UTC
