### ISSUE TITLE
Wrong Profit Calculation

### ISSUE THREAD

**Issue by arthurengeletrica** [taniman/profit-trailer#1863] opened 2018-05-14 19:24 UTC
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.04

 
Exchange:
- [ ] Bittrex
- [ ] Binance
- [x] Poloniex

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (16.04)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

The Bot should show a profit of about 1.2% on PAIRS log, and SALES LOG of ZEC-BTC bought on 16:54 UTC May.14.2018 at
Cost: 0.00210000
Rate: 0.03539000

and sold on: 17:20 UTC May.14.2018 at:

Cost: 0.00212139
Rate: 0.03584000

## Current Behavior
It showed a wrong profit of more than 38% at PAIRS LOG some seconds before selling it and showed wrong bought price of about 0.02585 

![image](https://user-images.githubusercontent.com/38858258/40018933-235af8cc-5794-11e8-877b-657cba9036af.png)

which is impossible because the price was too far from reaching this value at this day of May.14.2018 as can be seen here:

![image](https://user-images.githubusercontent.com/38858258/40019112-ad815122-5794-11e8-9f7a-4ffc5556180b.png)

And shows wrong profit and bought price also on SALES LOG

![image](https://user-images.githubusercontent.com/38858258/40018957-337a28fe-5794-11e8-85ae-f6d4ac4a3598.png)

## Troubleshooting

I don't know if I can fix it

## Possible Solution

I don't know what is causing it

## Steps to Reproduce

1. Just using normally the 2.04 version without making any DCA buy and waiting for selling time

## Configuration

PAIRS:

https://pastebin.com/QKuMzwtE

DCA:

https://pastebin.com/bWW8BZPn

INDICATORS:

https://pastebin.com/iP4FEraD

## Log files/console output

 

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2002302/ProfitTrailer.log)

**Comment by alexdolli** [comment] 2018-05-14 19:50
Same problem here (Binance)

**Comment by SgtBatten** [comment] 2018-05-14 19:54
@alexdolli
Can you not tick the checkbox for binance in the OP? I can but can you as a regular user?

**Comment by arthurengeletrica** [comment] 2018-05-14 20:03
Alex, have you posted your issue too?

**Comment by SgtBatten** [comment] 2018-05-14 20:05
They just did by commenting here....

**Comment by SgtBatten** [comment] 2018-05-14 20:15
Duplicate of #1859

**Closed by SgtBatten** 2018-05-14 20:15 UTC

**Comment by alexdolli** [comment] 2018-05-14 21:06
Hey SgtBatten, I was not aware that I am supposed to do that. But to answer your question, no I cannot.

**Comment by SgtBatten** [comment] 2018-05-14 21:25
Thanks for confirming @alexdolli

I have done it for you on the consolidated version of this issue.
