### ISSUE TITLE
Seems like the exchange is spitting out invalid data

### ISSUE THREAD

**Issue by crack00r** [taniman/profit-trailer#795] opened 2018-01-24 14:31 UTC
2018-01-24 15:28:03 ERROR ProfitTrailerService - Seems like the exchange is spitting out invalid data. Let's wait 5 minutes and see Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive

**Comment by crack00r** [comment] 2018-01-24 14:32
My bot is spaming this error, over and over.
i trade on Binance

**Comment by crack00r** [comment] 2018-01-24 14:57
![image](https://user-images.githubusercontent.com/6163329/35338877-5353f16c-011f-11e8-89bd-0640ad458083.png)

**Comment by argon1199** [comment] 2018-01-25 00:56
Experience this error too.  Restarting my bot worked for me.

**Comment by crack00r** [comment] 2018-01-25 02:50
Yes i know .. for a short time...
But maybe they should this bug asap...
Cant restart the bot the hole day

**Comment by mishaaltk** [comment] 2018-01-25 03:14
I'm getting this too. Looks like a bug in the new .12 version.
The whole purpose is to let it run overnight, for days and weeks without fiddling around with it. Can't get banned every few seconds and restart the bot!

**Comment by cgminer997** [comment] 2018-01-27 22:35
I just downloaded v12 and exact same error. Are you guys going to do something or don't give a shit... just collected btc and happy...
Do something or return my money...

**Comment by cenedex** [comment] 2018-01-30 06:41
has this been resolved?  i just bought this and installed it and im getting this error.

**Comment by cristianserban** [comment] 2018-01-30 06:43
hi
we are currently testing a new release which will contain also a fix for this. 
as soon as it has the aprove we will release it.

**Comment by cenedex** [comment] 2018-01-31 04:33
Ok. Thanks.  Do you have an estimate of when  this will be released.




Get Outlook for Android







On Mon, Jan 29, 2018 at 10:43 PM -0800, "Cristian Serban" <notifications@github.com> wrote:












hi

we are currently testing a new release which will contain also a fix for this.

as soon as it has the aprove we will release it.

**Comment by DennisCeran** [comment] 2018-01-31 19:28
hi everybody. i have the same problem. when can we exspect an answer?

dennis from holland

**Comment by alpine008** [comment] 2018-02-03 05:01
hello ... I've just purchased and have the same error --- ETA on a fix? thanks!!

**Comment by zigzag-way** [comment] 2018-02-04 20:36
Getting the same error on one of my laptops. All the time...
I have to launch it for about 10 times to get it running without error.

**Comment by adnannpk** [comment] 2018-02-05 05:18
I updated my bot this morning and it was working fine, had to restart my PC and now getting this same error :(

**Comment by adnannpk** [comment] 2018-02-05 05:21
Restarted my bot twice actually worked now it is not showing any error

**Comment by BPSOrdina** [comment] 2018-02-06 21:39
Any fix for this?

**Comment by alyseight** [comment] 2018-02-08 18:49
I have the same problem as well running on a linux vps using Binance.

**Comment by meinit** [comment] 2018-02-09 16:55
Me to, resarting does not help ;-(

**Comment by taniman** [comment] 2018-02-09 19:12
this is not a bug. setup errors and connection errors on your VPS are causing this. the errors states

**Closed by taniman** 2018-02-09 19:12 UTC
