### ISSUE TITLE
PT stops trading and no possible buy log

### ISSUE THREAD

**Issue by ManuGithu** [taniman/profit-trailer#1012] opened 2018-02-07 08:20 UTC
v1.2.6.15
OS: Debian 
Exchange: Binance

After running correctly for several hours, PT stops trading and the possible buy log is empty.  Pairs and DCA logs still contains pairs.

At the time the issue occurs, I do not see any suspicious messages in profit-trailer-out-0.log and profit-trailer-error-0.log

However the traffic to the binance server stopped.

**Comment by ingeniumdesign** [comment] 2018-02-07 08:44
here the same.
the *-HeartBeat works all fine, bot works fine, and no error in the log.
but the coin-value is not correctly/refresh

after a restart, all works for a xx time perfect.

**Comment by BeldarConehead** [comment] 2018-02-07 11:11
Same here. No errors or warnings, heartbeat is fine. 
v1.2.6.15
OS: macOS 10.13.3
Exchange: Binance

I also run a bot on Bittrex with same OS and version and it doesn't exhibit this issue. I initially noticed it due to the $700 difference in the price of BTC on the Monitor page between Binance and Bittrex. I just upgraded from v1.2.6.9 and I would regularly go for a week at a time and never restart, and when I did it wasn't because it quit working.

**Comment by JulesBern** [comment] 2018-02-07 11:25
Happening here as well. It's as if logs don't really log anything.

**Comment by usslindstrom** [comment] 2018-02-07 11:40
Ditto.  same issue. 

both on ubuntu desktop and server v16

thinking of adding a scheduled task of killing the services and relaunching

**Comment by YoJeff** [comment] 2018-02-07 14:21
Duplicate of a duplicate duplicate.

**Closed by YoJeff** 2018-02-07 14:21 UTC
