### ISSUE TITLE
ERROR ProfitTrailerService - Call to GetOrderHistory was throttled

### ISSUE THREAD

**Issue by BOBALLEX** [taniman/profit-trailer#1799] opened 2018-05-06 20:47 UTC
ERROR ProfitTrailerService - CB - Call to GetBalances was throttled. Try again in 60
2018-05-06 23:11:10 ERROR ProfitTrailerService - TH - Call to GetOrderHistory was throttled. Try again i
2018-05-06 23:11:11 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-05-06 23:11:22 ERROR ProfitTrailerService - CB - Call to GetBalances was throttled. Try again in 60
2018-05-06 23:11:23 ERROR ProfitTrailerService - TH - Call to GetOrderHistory was throttled. Try again i
2018-05-06 23:11:23 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-05-06 23:11:35 ERROR ProfitTrailerService - CB - Call to GetBalances was throttled. Try again in 60
2018-05-06 23:11:35 ERROR ProfitTrailerService - TH - Call to GetOrderHistory was throttled. Try again i
2018-05-06 23:11:36 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-05-06 23:11:47 ERROR ProfitTrailerService - CB - Call to GetBalances was throttled. Try again in 60
2018-05-06 23:11:48 ERROR ProfitTrailerService - TH - Call to GetOrderHistory was throttled. Try again i
2018-05-06 23:11:49 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in

HOW TO SOLVE THIS PROBLEM? I AM USING BITTREX EXCHANGE

**Comment by SgtBatten** [comment] 2018-05-06 21:40
Duplicate of #1593

**Closed by SgtBatten** 2018-05-06 21:40 UTC
