### ISSUE TITLE
Feature Request - Limit buy orders instead of market orders

### ISSUE THREAD

**Issue by clickstudio** [taniman/profit-trailer#1502] opened 2018-03-26 03:07 UTC
Once a pair's buy conditions are met , I would love to be able to place a buy limit order at the bid price (or slightly above) instead of the bot buying at market (from the ask). Trades are always immediately down by the pair's spread which seems to give up a lot of potential profit sometimes.

For example, if you're trying to get a 1% gain and your market spread is 1%, the bid price actually has to move 2% to get done. If the initial purchase was placed on the bid and got hit, the bid price only has to move up by 1% for the same result.

I guess there would need to be a function to check the status of the buy order and if it was partially filled, adjust the order upward etc.

**Comment by clickstudio** [comment] 2018-03-26 05:03
Also added here;

https://github.com/taniman/profit-trailer-enhancements/issues/240

**Comment by YoJeff** [comment] 2018-03-26 15:07
Logged in enhancements, not a bug -- closing.

**Closed by YoJeff** 2018-03-26 15:07 UTC
