### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by ajohn47708** [taniman/profit-trailer#657] opened 2018-01-12 03:12 UTC
Error reading file null.

**Comment by cristianserban** [comment] 2018-01-12 09:27
hi
Does the bot starts ?
https://wiki.profittrailer.io/doku.php/common_errors#error_util_-_error_reading_file_null

ERROR Util - Error reading file null
NOTE This error should not appear after PT version 1.2.6.9, as the problem is automatically fixed in the event of a crash. If you experience this error, upgrade to at least this version or later.

Full error message:

ERROR Util - Error reading file null
or

Error reading file java.lang.illegalstateException: Expected 
BIGIN-OBJECT but was STRING at line 1 column 1 path $ou ERROR ProfitTrailerService - Handled exception com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept 
malformed JSON at line 2 column 2 path $
This error will show when the ProfitTrailerData.json ​file is corrupted, mostly caused by a computer ​crash or an incorrect ​shutdown.

There is a backup ​of that file named ProfitTrailerData.json.backup ​in the same folder. So to fix this issue:

Stop ProfitTrailer
Delete the ProfitTrailerData.json ​file and copy the ProfitTrailerData.json.backup ​file to ProfitTrailerData.json
Start ProfitTrailer ​again

**Closed** 2018-01-12 09:56 UTC
Labels: documentation, wontfix

**Comment by ajohn47708** [comment] 2018-01-12 13:50
Bot doesn't start
