### ISSUE TITLE
Error occured in ticker - incorrect data. Anyone else having this issue?

### ISSUE THREAD

**Issue by MindWallet** [taniman/profit-trailer#1820] opened 2018-05-09 07:38 UTC
Hello,

I suddenly got this message on my bot running on Profit Trailer 2.0 on Binance. Never had this issue before:

ERROR ProfitTrailerService - Error occured in ticker, message We got incorrect data, retrying, result:

I checked Binance, and it seems everything is OK there. Anyone else having this issue? Anyone know how to solve it? Thanks!

**Comment by TrueOsiris** [comment] 2018-05-09 07:41
crosspost/duplicate of issue #1819

**Comment by MindWallet** [comment] 2018-05-09 07:42
I tried to find a similar post, but apparently did not succeed. You can close this. Thanks.

**Closed** 2018-05-09 07:43 UTC
