### ISSUE TITLE
Loss of Pending Logs and Possible Buy Database Error

### ISSUE THREAD

**Issue by pwankey** [taniman/profit-trailer#1620] opened 2018-04-23 22:18 UTC
After migration to version 2.0
1. Lost some pending log record. Pending table has no date column
2. Possible Buy returns error: "DataTables warning: table id=dtPossibleBuysLog - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3" --- Resolved - error was due to omission of Buy strategy in the pairs file... Issues 1 and 3 still exist.
3. PT crashes often

**Comment by SgtBatten** [comment] 2018-04-24 11:01
Duplicate of #1562

**Closed** 2018-04-24 14:38 UTC
Labels: duplicate
