### ISSUE TITLE
Bb Trigger is higher than Current BB

### ISSUE THREAD

**Issue by icemancometh** [taniman/profit-trailer#1392] opened 2018-03-09 16:23 UTC
My buy value = - 15 and when I look at my possible buy logs my BB trigger is higher than the current BB.

Not all my possible buy logs are higher. Some are lower as well. 

How do I fix this?

**Comment by taniman** [comment] 2018-03-10 08:04
You fix it by putting a positive value. 
Postive values go inwards. negative goes outwards. For BB

**Comment by icemancometh** [comment] 2018-03-10 19:16
Exactly. I have a negative buy value which means it should be outside of the current BB but instead it is inside. Which is wrong. I dont want it inside the BB, I want it outside, which is why I have set a negative buy value. 

This issue shouldn't have been closed.

**Comment by taniman** [comment] 2018-03-10 20:31
This higher triggers is most likely caused by  trailing. We pin down the original trigger while trailing. 

Try disabling trailing and restart the bot. than report your findings.

**Comment by icemancometh** [comment] 2018-03-12 01:40
Here is a screenshot of what I am seeing. At this point, this is my buy parameters:
ALL_buy_strategy = LOWBB
ALL_buy_value = -5
All_trailing_buy = 0.25
![b4 reset trailing buy](https://user-images.githubusercontent.com/37220890/37261627-09c31322-256c-11e8-9c28-f72291366f60.PNG)

Here is a screenshot of the PBL after I set the trailing buy to 0 and reset the bot:
![after trailing buy](https://user-images.githubusercontent.com/37220890/37261674-552349f4-256c-11e8-9535-256f1edae9bb.PNG)

It looks like that solved the problem temporarily; however, I would like for there to be a trailing buy when I run LOWBB. Is there a permanent fix?

**Comment by taniman** [comment] 2018-03-16 13:39
Trailing works. But the stored value sometimes reappears and well it's confusing to people
I will be rethinking and reworking the trailing logic for version 2.0 which should be released in a few weeks

**Closed by taniman** 2018-03-16 13:39 UTC
