### ISSUE TITLE
Sales not written to PTData.json

### ISSUE THREAD

**Issue by Nephor80** [taniman/profit-trailer#1759] opened 2018-05-02 17:32 UTC
PT2 is working correctly except the last 2 days. PT2 shows several sales on that days, but it seems they are not written to the ...Data.json. So other programs like PT Magic show 0 sales.
A restart didn't solve this issue.
Is this a bug or an API-Problem?
THX

**Comment by Nephor80** [comment] 2018-05-02 18:04
After a restart, all Sales happening the last two days are lost.

**Comment by SgtBatten** [comment] 2018-05-04 09:33
Duplicate of #1720

**Closed by SgtBatten** 2018-05-04 09:33 UTC
