### ISSUE TITLE
Telegram repeated message

### ISSUE THREAD

**Issue by louisswart** [taniman/profit-trailer#295] opened 2017-11-25 07:40 UTC
The following Telegram message repeats sometimes 10 to more than a 100 time in the chat.

`Bittrex Profit Trailer - Ticker update - There is something wrong with your Bot, please restart`

**Comment by SanderGith** [comment] 2017-11-25 15:03
Hi Elroy,

Programmer myself so I collected some data additional data for you as I also experienced this issue twice already.

I got the same errors last night and again this morning. After a restart they stopped and PT resumed duty, but it seems PT wasn't able to recover itself.

Running: PT version 1.2.5.6 running on windows 10 - Java 8 update 151

Details about the part of this morning:

I have made a screenshot snippet from the telegram part and also attached relevant part of the log file. So that it matches with the screenshot as close as possible.

Telegram screenshot:
![pt error](https://user-images.githubusercontent.com/33983565/33231540-01621d5e-d1f7-11e7-99ac-3483d371c0c3.png)

Log file:
- I made a relevant snippet of the log file
- For security reasons I cleared out all GUIDs (not sure if this should be posted public).
- I added some notes about what was executed and what wasn't

[ProfitTrailer snippet.log](https://github.com/taniman/profit-trailer/files/1503154/ProfitTrailer.snippet.log)

Hope you can look into it. If you need more details please contact me.

Cheers,

Sander

**Comment by SanderGith** [comment] 2017-11-27 09:04
Hi Krimson,

This looks like a different error. I assume you are not receiving some(?) telegram messages.  The issue this ticket is related to receiving lots and lots of tg messages about the bot not working. Can you create a separate ticket for this?

Groeten,

Sander

**Comment by krims0n32** [comment] 2017-11-27 09:06
Nope, it's the exact same problem. Lots of Telegram messages, like 3000 if I haven't checked in a while.

Ticker update - There is something wrong with your Bot, please restart

**Comment by SanderGith** [comment] 2017-11-27 18:47
Well if it's the same issue, then welcome to this ticket :-D

**Comment by louisswart** [comment] 2017-11-27 22:16
I've increased memory on both,:
1) the program execution using "-Xmx512m -Xmx512m" and 
2) the VPS only had 786M that I increased to 1024M.

I have not had this issue since these changes.

**Comment by SanderGith** [comment] 2017-11-27 22:19
I also have the memory set to 512m. Not sure if I had it at that, at the moment the errors occurred. I'll keep monitoring and update the ticket accordingly

**Comment by krims0n32** [comment] 2017-11-28 08:48
Not sure it is memory related. I had the issue with -Xmx768m -Xms768m as well (on a 2GB server).

**Comment by taniman** [comment] 2017-11-29 13:26
I have dialed down the error reporting in upcoming release. But it will be displayed whenever there is something wrong with your bot. So please  restart your bot ;)

**Closed by taniman** 2017-11-29 13:26 UTC

**Comment by krims0n32** [comment] 2018-01-03 12:46
I am still getting this error a few times a week on Bittrex. What causes this? It is kind of annoying having to restart the bot this often.

**Comment by adamf2001** [comment] 2018-01-16 00:02
Same here brand new bot (v1.2.6.10) - running with settings from gnome pack v9.1, basic low funds, single pair, one at a time as I’m just starting out.  Taniman is saying the message is correct and valid which is cool, the bot is doing exactly what it was designed to do but some config value is causing it to error - can anyone help identify this config value so that we can correct it and resolve the error?  I.e is the bot trying to buy something without enough funds? Or is there a conflict with the configuration vs the boundary’s or limits in the exchange (i’m on Binance) - any help or pointers would be much appreciated!
