### ISSUE TITLE
v2.0.2 STOCHRSI has bug

### ISSUE THREAD

**Issue by g001613001** [taniman/profit-trailer#1800] opened 2018-05-07 01:32 UTC
The true data not 0.000000
but browser show 0.000000
Please fix it, thx!
My indicator set 
STOCH_candle_period = 14400
STOCH_length = 14
My Pairs set
DEFAULT_D_buy_strategy = STOCHRSI
DEFAULT_D_buy_value = 0.2
DEFAULT_D_buy_value_limit = 0

![2018-05-07 9 27 27 copy](https://user-images.githubusercontent.com/18544298/39681021-7d9c105c-51d9-11e8-9601-5e2a8cd83351.png)

**Comment by SgtBatten** [comment] 2018-05-07 01:44
Duplicate of #1611

**Comment by SgtBatten** [comment] 2018-05-07 01:44
Also, stochrsi does not use STOCH candle period

**Closed by SgtBatten** 2018-05-07 01:44 UTC
