### ISSUE TITLE
PT 2.0 API calls getting throttled on Bittrex

### ISSUE THREAD

**Issue by vbootstrap** [taniman/profit-trailer#1566] opened 2018-04-21 05:29 UTC
I am getting this output:
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.9.RELEASE)

2018-04-21 01:27:38 INFO Application - PT Version: 2.0
2018-04-21 01:27:38 INFO Application - Java Version: 1.8.0_161
2018-04-21 01:27:47 INFO ProfitTrailerService - Cache Heartbeat
2018-04-21 01:27:48 INFO ProfitTrailerService - PAIRS Heartbeat
2018-04-21 01:27:48 INFO ProfitTrailerService - DCA Heartbeat
2018-04-21 01:28:17 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:18 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - TH - Call to GetOrderHistory was throttled. Try again i
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - TH - Call to GetOrderHistory was throttled. Try again i
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - TH - Call to GetOrderHistory was throttled. Try again i
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:19 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:20 ERROR ProfitTrailerService - TH - Call to GetOrderHistory was throttled. Try again i
2018-04-21 01:28:20 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:20 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:20 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-21 01:28:20 ERROR ProfitTrailerService - TH - Call to GetOrderHistory was throttled. Try again i
2018-04-21 01:28:20 ERROR ProfitTrailerService - TH - Call to GetOrderHistory was throttled. Try again i
2018-04-21 01:28:24 ERROR ProfitTrailerService - CB - Call to GetBalances was throttled. Try again in 60
2018-04-21 01:28:24 INFO a - API Problems?

When I enable Telegram I get the following as well:

Ticker update - There is something wrong with your Bot, please restart

**Comment by QXR987** [comment] 2018-04-22 20:02
I am getting the same errors  Throttled and "Ticker update - There is something wrong with your Bot, please restart"

**Comment by FSS421077** [comment] 2018-04-24 22:09
I am receiving the same error (ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in...) with Profit Trailer ver 1.2.6.25 as well.

**Comment by upthedownstairs** [comment] 2018-04-25 02:07
I changed my connection.timeout to 40 in the application.properties and it seems to be working, however my telegram bot is blowing up now.

**Comment by lukecrypto** [comment] 2018-04-25 02:26
I too am having this issue. Will try @upthedownstairs suggestion to hange the timout when i get home and report my results.

**Comment by upthedownstairs** [comment] 2018-04-25 11:44
Still happening but doesn't seem to be as often. I don't think it has anything to do with the connection timeout, unfortunately.... @lukecrypto

**Comment by followbtcnews** [comment] 2018-04-25 15:12
The problem is Bittrex has changed and lowered the REST API call limits. The only way to fix is for PT to update and change over to websocket instead of Rest api on Bittrex

**Comment by keithofaptos** [comment] 2018-04-25 18:18
This is happening in V1:25 also .Is this going to be adjusted for V1 users when WS gets coded ?

(Because I'm not changing over to V2.0 until V2.1 is out. Already read the V2 wiki , looks great.But with
V2 having all these issues (problems) i'm not interested in spending time Beta testing it . )

**Comment by lukecrypto** [comment] 2018-04-25 20:56
@upthedownstairs agreed. Changing to a timeout of 40 hasn't eliminated the problem.

Let's hope that an update will be released addressing the problem that @followbtcnews has identified.

**Comment by upthedownstairs** [comment] 2018-04-25 21:50
Still seeing this issue on version 2.0.1 for Bittrex, however it's not as bad as it was earlier... unless of course the past 10 minutes I've just been lucky.

**Comment by SgtBatten** [comment] 2018-04-25 21:57
Bittrex is a more complicated rewrite of the API calls. Binance was simpler.

**Comment by FedericoMurtula** [comment] 2018-04-26 12:16
Im getting this error with a couple of APIs of Bittrex: buylimit, selllimit. Also when I try to download the Orders History by the website. (The following errors were encountered:
Call to DownloadFullOrderHistory was throttled. Try again in 60 seconds.
Please correct these issues and try again.).


I think is Bittrex issue. They suck.

**Comment by Richo005** [comment] 2018-04-27 11:42
Same issue here

**Comment by ricardodacosta** [comment] 2018-04-27 12:11
Is there anything we can do to limit the amount of API requests?

**Comment by SgtBatten** [comment] 2018-04-27 12:14
Not that I know of sorry

**Comment by gregmdesign** [comment] 2018-04-27 21:39
i have the same problem and i'm testing with a Whitelist i read somewhere that it can help. an other way is to reduce de number of pair to trade but i'm not sure for the moment. I test something and i return back to you

**Comment by FSS421077** [comment] 2018-04-27 22:16
All,

Check this out from Bittrex.  PT needs to have WS API vs REST API.  PT Devs need to look into this.
https://support.bittrex.com/hc/en-us/articles/360002152712-Bittrex-Beta-API-Documentation

**Comment by SgtBatten** [comment] 2018-04-27 22:25
Yes we know. It has to be recoded.

**Comment by gregmdesign** [comment] 2018-04-27 22:54
How many times do you think it takes to change the code? Do you think this is a risk to be banned by Bittrex for spamming the api if we continue like this?

**Comment by SgtBatten** [comment] 2018-04-27 23:25
No there is no risk. This is being worked on as a priority. We are sorry for the inconvenience

**Comment by gbrottman** [comment] 2018-04-28 07:08
Please do not forgot V1 ...... thank you

**Comment by SgtBatten** [comment] 2018-04-28 07:44
well v1 was never meant to have any more patches, im unsure if bittrex will get a patch on v1

**Comment by gbrottman** [comment] 2018-04-28 22:54
That’s tragic. I’m afraid to upgrade. Mainly because of feeder, the upgrade looks complicated to a novice

**Comment by philwmich** [comment] 2018-04-28 23:13
I haven’t used feeder since switching to V2. Setting up feeder on V1 is
more complicated than setting up V2

**Comment by FSS421077** [comment] 2018-04-29 00:15
@gbrottman PT Feeder has been upgraded and now supports PT 2.0.  Current release 1.5.1.685, however start off with v. 1.5.1.670 first then upgrade.

https://github.com/mehtadone/PTFeeder/releases

**Comment by gbrottman** [comment] 2018-04-29 05:51
Is there a solution to this issue?

2018-04-29 01:47:57 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-29 01:47:57 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-29 01:47:57 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-29 01:47:57 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in
2018-04-29 01:47:57 ERROR ProfitTrailerService - OO - Call to GetOpenOrders was throttled. Try again in

**Comment by SgtBatten** [comment] 2018-04-29 06:10
It will be fixed in a patch as soon as we can.

**Comment by gbrottman** [comment] 2018-04-29 19:26
Thank you for your response. 

Can PT Feeder release 1.5.1.685 and / or release 1.5.1.670 be used with Profit Trailer V1?

**Comment by CrypTony22** [comment] 2018-04-30 12:45
Any chance the patch will also be released for v1?

**Comment by gregmdesign** [comment] 2018-05-03 07:50
Hi, any news about the MAJ ??

**Comment by ramonduraes** [comment] 2018-05-04 16:51
+1

**Comment by RealTImThomas** [comment] 2018-05-07 18:08
Any news on a throttle fix?

PT 2.0.2 has become almost useless with Bittrex!!!
I went from 1.25-2.5% profit per day on Bittex to 0.02% to 0.00 on most days now.

Binance bot is working great, getting 1.5-2.5% per day on PT 2.0.2 

Anyone getting Bittrex to not get the throttle on PT 2????
This is getting more than frustrating... I'm about to move everything over Binance if there isn't a fix soon.

**Comment by lukecrypto** [comment] 2018-05-07 20:54
Unfortunately the update has done next to nothing for my Bittrex throttle issues. I do appreciate that the development team is trying, though.

**Comment by SgtBatten** [comment] 2018-05-07 22:07
2.0.3 has some new parameters which we can use to slow bittrex down to avoid the 1 minute cooldowns. We'll get it out as soon as we can. This will give us some breathing room to finalise the API rewrite

**Comment by username77** [comment] 2018-05-09 08:00
@YoJeff maybe v1 is dead but v2 is born very badly. V2 seems full of bugs. You can see from here or from many reviews on the internet/youtube. Here are not asking to add tools, websockets, apis, exchanges, layouts. they only ask to limit requests to bittrex from >60 calls/min to <60calls/min and dont think is so complicated. In this way you give a service to those who want to stay in the old version spending only 10min of programming/compiling. As a developer I would never allow myself to put into production a product so full of errors.

**Comment by RealTImThomas** [comment] 2018-05-09 16:11
Running 2.0.3
Still getting throttle, just not as bad as before.

Looks like you are going in the right direction, just not all the way there yet.
Actually getting some trades today, Bittrex not totally useless for me today.

Thanks, keep up the hard work.
T

**Comment by RealTImThomas** [comment] 2018-05-09 19:57
Getting a new error message in 2.0.3

a  -  slow down 30 seconds

so it looks like a different version of a throttle with Bittrex
getting the throttle message about once an hour, getting the slow down at random intervals.

T

**Comment by RealTImThomas** [comment] 2018-05-15 13:37
Just loaded up 2.0.4 this morning....
just got 2 of the "slow down 30 seconds" messages on boot up.... but after that, nothing.
It seems to have fixed the throttle problem and slow down problem.
One hour and no error messages so far.

Good job guys, that may have done it on the Bittrex side.

Now on the Binance side 2.0.4 doesn't work at all, I needed to go back 2.0.3 to get Binance to work.

**Comment by YoJeff** [comment] 2018-05-16 03:05
Merge #1873

**Closed by YoJeff** 2018-05-16 03:05 UTC
