### ISSUE TITLE
auto restart broken

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer#367] opened 2017-12-06 08:41 UTC
[ProfitTrailer (7).log](https://github.com/taniman/profit-trailer/files/1534399/ProfitTrailer.7.log)

**Comment by kennethkalmer** [comment] 2018-01-05 22:08
It seems to be the `"autorestart": false` in `pm2-ProfitTrailer.json`. Simply removing the line and restarting ProfitTrailer with the new settings solves this.

This is duplicate of #308 as well

**Comment by taniman** [comment] 2018-01-05 22:29
@kennethkalmer tnx for input, but most users do not use pm2 and still get a problem with this. Because all processes are not closed correctly so the ports remain in use

**Comment by kennethkalmer** [comment] 2018-01-05 22:44
I think the default pm2 config should at least be configured this way so people don't get a nasty surprise.

We tested these changes with reboots and randomly applying `kill -9` to the PT instances and seeing pm2 bring them back to life as expected.

**Closed** 2018-02-23 09:58 UTC
Labels: wontfix
