### ISSUE TITLE
Case sensitive or case-sensitive?

### ISSUE THREAD

**Issue by tash649** [taniman/profit-trailer#1653] opened 2018-04-25 14:31 UTC
is there a difference between DEFAULT_Max_Trading_Pairs and DEFAULT_max_trading_pairs? what will work and what not? and BCH_Dca_Enabled or BCH_DCA_Enable

**Comment by YoJeff** [comment] 2018-04-25 15:09
Best practice is the use the correct/defined case always.

**Comment by tash649** [comment] 2018-04-25 15:10
can you please answer the question? @YoJeff

**Comment by YoJeff** [comment] 2018-04-25 15:11
Just assume yes.   Case matters pretty much everywhere but Windows filenames.

**Comment by YoJeff** [comment] 2018-04-25 15:12
Not a bug.   Closing.

**Closed by YoJeff** 2018-04-25 15:12 UTC
