### ISSUE TITLE
DCA pair loses price average after partial sale

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer#1879] opened 2018-05-17 21:54 UTC
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.5

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Keep the average price
## Current Behavior
I had two pairs in DCA which only sold partially. After the partial sale, it lost the average price for those pairs. Had to manually add it back in HotConfig.

## Steps to Reproduce

1.
2.
3.
4.

## Log files/console output

 
Sorry, I can't provide a log file. It happened yesterday morning and I didn't even notice it until today. I restarted the bot twice since it happened.

**Comment by SgtBatten** [comment] 2018-05-17 22:15
log file is perpetual. unless you deleted it, you have it

**Comment by SgtBatten** [comment] 2018-05-17 22:15
#duplicate of #1725

**Closed by SgtBatten** 2018-05-17 22:15 UTC
