### ISSUE TITLE
Sales log buy and sales entry errors... Bot selling and immediately rebuying... Bot selling quickly at a loss... Sales log entries do not match exchange...

### ISSUE THREAD

**Issue by TheBigShort111** [taniman/profit-trailer#1120] opened 2018-02-16 06:41 UTC
PT Version 1.2.6.16
Mac OS High Sierra
Binance Exchange

I know this has been brought up in one form or another, but this issue seems to be gaining traction. This issue has been happening to me very often recently. The bot places and order to buy, then reports the "bought price" which is often inaccurate (happening with greater frequency) - This throws off the amount to sell at a profit.

Additionally, the bot has been selling then immediately rebuying the same pair it just sold.

The third issue I'm having is that the bot is selling these "rebuys" quickly at a small loss. There is no rhyme or reason when it happens... It has happened on each trading pair for me so far.

As you can see, the sale log data does not match the exchange, and there are instances where the prices are wrong, and the bot sold for a loss, and the bot sells, then rebuys... All happening at the same time in instances. So this means that my sales log is off, showing a profit when it sells for a loss. Also, the sales log shows an expired sell as a completed sell (compared to the exchange, so the sale log tally is off as well.

Perhaps instead of PT creating the sales log from local data, it could fetch the actual sales data from the exchange? (or some sort of hybrid version of that)

![screenshot 2018-02-16 00 58 24](https://user-images.githubusercontent.com/36313988/36295488-e1a5c74a-12b5-11e8-8266-90651d38e445.png)
![screenshot 2018-02-16 01 04 00](https://user-images.githubusercontent.com/36313988/36295490-e1be3708-12b5-11e8-8c66-29cde34e29d3.png)
![screenshot 2018-02-16 01 07 13](https://user-images.githubusercontent.com/36313988/36295491-e1ca3d5a-12b5-11e8-871f-79e1eb141213.png)

**Comment by Pennypacker85** [comment] 2018-02-16 09:23
I am having the same issue with the bot rebuying. Also, when it does it often does so outside of my EMAGAIN requirements. Eg:
buy is set for -0.85,  it sold after a huge spike, EMA's are both sitting around 0.00047 and it sold at 0.000488 then rebuys at 0.00049 Well above the current EMA... Can't pinpoint any reason why it is doing this but it is one of the major causes of my DCA bags...

Any help would be appreciated.

**Comment by taniman** [comment] 2018-02-16 13:59
@TheBigShort111 I have 1 question for you.

If the bot bought 0.03512
how is it possible to sell 0.03513??

so to me it seems like the bot merged your with your previous accumulated dust and this is why it counted a different average value and thus sold at a profit.

Can you filter by BCC/USDT so I can see what was your previous BCC/USDT purchase?

I am going to release a version to slow down the fast repurchase

**Comment by jas-jas** [comment] 2018-02-16 14:48
I'm not sure how the local data is incorrect if it's pulling it from the exchange at some point in time, but that's obviously what is happening. This seems like an easy fix, which would also seem to fix the issue with the missing buy price for pairs as well which need to be set manually in the hotconfig. I'm not sure why the bot can't pull that data from the exchange.  The problem is very similar to my issue https://github.com/taniman/profit-trailer/issues/1110 which is related to sells for losses and the bot ignoring buy limits in the PAIRS file.  If it is picking up incorrect prices from dust or from a previous buy, that is the problem which needs to be fixed, and with the correct buy/sell ledger on the exchange that would seem to be an easy kill.

**Comment by drummerboy5408** [comment] 2018-02-16 15:05
If it helps, Heres my data from a fast repurchase my bot just did with EMASPREAD. not sure what the problem is at all but I hope it helps

![wtf2](https://user-images.githubusercontent.com/33564610/36313822-8478ffd6-12f8-11e8-9e85-bb827431890f.JPG)

**Comment by TheBigShort111** [comment] 2018-02-16 17:52
@taniman  Sure, here's the data...

For starters, If there was dust factored into the equation, then it was dust created by PT as I had not previously traded BCC. That said, however, this issues does, in fact seem somehow to be related to coins with dust, as each time there is a discrepancy it is from a coin with dust, but again, keep in mind that any of this dust is being created while using PT, not prior (with the only possible exception in my case being BTC)

Either way, in a sell order, it would be nice if PT could determine the dust portion of a trade (when applicable) and perhaps not use the dust basis as the bought cost for the entire sale, it shows a very misleading and inaccurate representation of the sale in the logs... If my dust base was at bought cost of $100.00 and I have $.01 in dust, then a sell order for a coin fills at $150.00 with a bought cost of $120.00 (a 25% actual gain), the sales log entry (if it includes the dust) will show the same order as having a $100 bought price and a $150.00 sell price for a 50% gain, which is not accurate as the 50% gain was only on the $.01, not the $120.00 - Of course I fully understand that the actual calculated profit would be accurate, but the sales log profit% shows a grossly different amount.

Also, because PT does not grab/monitor the actual exchange order history to create the sales log, there are instances where an expired sell order on the exchange is reported as an actual sale in the PT sales log.

These facotrs combined seem to be partially responsible for the issue of value misreporting in the monitoring page and the sales log.

![screenshot 2018-02-16 12 25 39](https://user-images.githubusercontent.com/36313988/36320833-9e12d652-1315-11e8-9fc3-90d13762f4d2.png)
![screenshot 2018-02-16 12 25 49](https://user-images.githubusercontent.com/36313988/36320834-9e253108-1315-11e8-9b47-fc6e210b3266.png)

Hopefully this helps you figure out a solution. As you can see, there are others experiencing the same issues as I - Also understand that we are all just trying to help you make PT better, surely I speak for other as well as myself when I say that I'm a fan of PT... Keep up the great work!

**Comment by taniman** [comment] 2018-02-16 18:19
@TheBigShort111 I see the previous sell for this coin was correct. So one question. as you receiving affiliate commissions on this account?

**Comment by TheBigShort111** [comment] 2018-02-16 19:00
@taniman  Yes- I have one referral which came after I started using PT... The total commission as of today from that referral is 0.00003444 BTC (of course that BTC total is comprised of very very small amounts of the base coins in which the referral bought and sold. He has been a referral since 1/28/18

Here is a situation with inaccurate sales log reporting, and what seems to be a sale at a loss... Just so you know, in case this affects the way PT looks at data on the exchange, I had made a deposit to my Binance account in ETH, and manually sold it to turn it into USDT, then have let PT handle trading it since... This happened before the roundtrip trade at the loss - In other words, this did not happen in the middle of any trades. So it seems not only did PT make the trade at a loss, but it shows in the sales log as a 5.24% gain... The bought and sold amounts and the dollar gain are not accurate either. PT shows a USDT gain of $2.59442038, but the Binance order history shows a loss of (-$0.24) - While I am not certain that this is the case, what it seems like to me is that PT takes the dust bought price and uses that as the basis for the trade, then sells when the trigger hits over that false base price for the whole trade, resulting in not only a loss, but also a misrepresentation of a gain in the sales log... I hope this helps...
![screenshot 2018-02-16 13 48 08](https://user-images.githubusercontent.com/36313988/36324205-a6cfc8ac-1321-11e8-9cc8-32665f2bdbce.png)
![screenshot 2018-02-16 13 48 26](https://user-images.githubusercontent.com/36313988/36324206-a6db6568-1321-11e8-8706-a8ca85438625.png)

**Comment by TheBigShort111** [comment] 2018-02-19 05:50
Here is yet another example when PT is making a buy, then immediate sell (at a loss) then a buy again right after. I'm feeling more confident now that the issue is not so much that PT has an issue with doing quick rebuys, so much as the issue is related to PT using the dust "bought" price as the base price when wrapped with a buy order later down the road, indicating the whole trade an artificially lower (significant at times) buy price than it is in reality. So, PT sees this "grouped" sell (the dust and new buy order) as having the artificial lower buy price (represented by the bought price of the dust) as compared to the "actual" bought price of the major part of the trade.

When the dust bought price is lower than the sell trigger, this creates an immediate sell of the brand new order. Then of course, once that artificially priced buy order sells, then PT rebuys because the original trigger criteria for the order still is current (as it should be)

So in effect, placing a limit on the time for a rebuy in this scenario does nothing to actually fix the underlying issue, which is the DUST bought price being used as the base for such orders. The correction for this dilemma could come in the way of overriding the dust bought price with the current order's "actual" bought price (as the dust often represents only a couple of cents or so, versus the actual new order which could be for tens, hundreds, or thousands of dollars)

Another possible fix would be to just eliminate the selling of dust inside a buy order. Frankly speaking, I honestly believe that this is the cause of several issues that people have been having with immediate sells, quick rebuys, and incorrectly reported/indicated profit gains.

It would seem there are a plethora of ways an account can accrue dust outside of PT, deposits from other exchanges, referrals... Not to beat a dead horse, but like I have said, the dust is usually very small fractions, typically splitting pennies, so why should this minuscule fraction of a trade be indicative of the whole order's bought price?

In my honest opinion, it seems that this all goes back to the incorporation of "dust" in an order being a root cause for these issues. Just my two cents of dusts worth.

For what it's worth, here is yet another example of what I'm talking about...

The trade in question indicates in my sales log that 0.00507600 BTC was bought @ 10408.73683544 ($52.84515691) then 56 seconds later 0.00507700 BTC was sold for 10735.01000000 (54.39264248) with an indicated profit of 2.93% for a USDT gain of $1.54748556 - However, that was not what actually happened...

Instead, what actually happened was: 0.00507600 BTC was bought @ 10751.31 (54.57364956) then 56 seconds later 0.00507700 BTC was sold for 10735.01000000 (54.39264248) for a loss of $.0467, or a total swing of accuracy in the sales log from a seemingly profitable 2.93% gain, to an actual loss.

This has happened on several of my trades (the ones I have caught) - But now I'm wondering how daunting it would be to go back to find all the trades where this has happened...

![screenshot 2018-02-18 23 42 10](https://user-images.githubusercontent.com/36313988/36363902-ca899db0-150e-11e8-8ee8-807ebde1789d.png)
![screenshot 2018-02-18 23 43 23](https://user-images.githubusercontent.com/36313988/36363903-ca949012-150e-11e8-8fd7-a705dc929380.png)


I'm probably speaking for a majority that would rather forego having their dust incorporated in a trade, if that trade will result in a losing one. The misreporting alone in the sales log is enough for me to waive the dust from the trades - Or as mentioned above, drop the dust bought price when incorporating it into the order, as it would represent a virtual insignificant change to the order it is incorporated into, versus using the fractionally insignificant amount of dust's bought price as the basis for the entire order, resulting in the aftermath of the buy/immediate sell/immediate rebuy scenario that we see play out.

Again, my sincerest hope is to provide information that will be beneficial to the community and provide feedback for the development of a better PT... Keep up the great work!

**Comment by TheBigShort111** [comment] 2018-02-19 07:30
Better yet... Any way to provide us with a command in the configuration file?

tradeDust=true/false

That would probably do it!

**Comment by taniman** [comment] 2018-02-20 15:15
LOL --> ```  Just my two cents of dusts worth. ```

Let me look into this tradeDust = true/false idea

**Comment by taniman** [comment] 2018-02-20 15:17
I will need your Discord name.

**Comment by taniman** [comment] 2018-02-20 15:19
@jas-jas  we always pull that from the exchange. There is nothing stored locally for calculations. Problem is when you start receiving affiliate commissions in your account for example. That data cannot be retrieve from binance as of yet. So the bot can't calculate prices

**Closed** 2018-02-23 09:56 UTC
