### ISSUE TITLE
The actual buying price is not in line with the display price. Binace is actually 0.002 but BOT shows that the income statistics deviation is too large and the actual income is 0.2, but BOT shows 20.

### ISSUE THREAD

**Issue by gh0st2017** [taniman/profit-trailer#1867] opened 2018-05-15 01:47 UTC
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

The actual buying price is not in line with the display price. Binace is actually 0.002 but BOT shows that the income statistics deviation is too large and the actual income is 0.2, but BOT shows 20.
## ProfitTrailer info
Version: 2.0 4

 
Exchange:
- [ ] Bittrex
- [ ##] Binance
- [ ] Poloniex

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [[centos6](url) ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by SgtBatten** [comment] 2018-05-15 02:27
No idea what you are saying. Please provide more information

**Comment by gh0st2017** [comment] 2018-05-16 01:35
DCA Sold in batches, the remaining coins will be priced at 0, resulting in a failure to continue selling.

**Comment by SgtBatten** [comment] 2018-05-16 01:49
in that case this is already am open issue, thanks.

**Comment by SgtBatten** [comment] 2018-05-16 01:50
Duplicate of #1725

**Closed by SgtBatten** 2018-05-16 01:50 UTC
Labels: awaiting information
