### ISSUE TITLE
Database may be already in use: "Server is running". Possible solutions: close all other connection(s); use the server mode; SQL statement:

### ISSUE THREAD

**Issue by echthard** [taniman/profit-trailer#2142] opened 2019-02-03 16:11 UTC
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.2.2

 
Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

 
Market:
- [X] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [X] Windows 10
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Current Behavior

Only one of three bots will crash with same error after wa while (couple of minutes?).

## Troubleshooting

Stop, Start. Stop. Start. Stop. Start.

## Steps to Reproduce

1.
2.
3.
4.

## Log files/console output

 

> 
2019-02-03 17:05:42 ERROR AppErrorController - org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
2019-02-03 17:05:42 ERROR GenericStrategyRunner - An error occured
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
        at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:431) ~[spring-orm-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:377) ~[spring-tx-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:461) ~[spring-tx-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:277) ~[spring-tx-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133) ~[spring-data-jpa-1.11.14.RELEASE.jar!/:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57) ~[spring-data-commons-1.13.14.RELEASE.jar!/:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at com.sun.proxy.$Proxy126.findAllByCurrencyPair(Unknown Source) ~[?:?]
        at nl.komtek.pt.services.data.CachedTradeHistoryService.a(CachedTradeHistoryService.java:21) ~[classes!/:2.2.2]
        at nl.komtek.pt.services.data.RepositoryService.f(RepositoryService.java:397) ~[classes!/:2.2.2]
        at nl.komtek.pt.services.ProfitTrailerService.b(ProfitTrailerService.java:449) ~[classes!/:2.2.2]
        at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:2.2.2]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:667) ~[spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$7dbd8cf0.b(<generated>) ~[classes!/:2.2.2]
        at nl.komtek.pt.strategyrunner.GenericStrategyRunner.b(GenericStrategyRunner.java:239) [classes!/:2.2.2]
        at nl.komtek.pt.strategyrunner.GenericStrategyRunner.genericStrategyRunner(GenericStrategyRunner.java:141) [classes!/:2.2.2]
        at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:109) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:136) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:254) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:262) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:214) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:56) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:189) ~[spring-orm-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:380) ~[spring-orm-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        ... 36 more
Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: "Server is running". Possible solutions: close all other connection(s); use the server mode; SQL statement:
10.55.237.59:61064/168b3eb3cee420efd006d8f7fb0367d117bd1a63799 [90020-197]
        at org.h2.engine.SessionRemote.done(SessionRemote.java:623) ~[h2-1.4.197.jar!/:?]
        at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:142) ~[h2-1.4.197.jar!/:?]
        at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:447) ~[h2-1.4.197.jar!/:?]
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:364) ~[h2-1.4.197.jar!/:?]
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124) ~[h2-1.4.197.jar!/:?]
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103) ~[h2-1.4.197.jar!/:?]
        at org.h2.Driver.connect(Driver.java:69) ~[h2-1.4.197.jar!/:?]
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:319) ~[tomcat-jdbc-8.5.32.jar!/:?]
        at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:212) ~[tomcat-jdbc-8.5.32.jar!/:?]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:736) ~[tomcat-jdbc-8.5.32.jar!/:?]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:668) ~[tomcat-jdbc-8.5.32.jar!/:?]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198) ~[tomcat-jdbc-8.5.32.jar!/:?]
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132) ~[tomcat-jdbc-8.5.32.jar!/:?]
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:106) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:136) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:254) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:262) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:214) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:56) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:189) ~[spring-orm-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:380) ~[spring-orm-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
        ... 36 more

**Comment by taniman** [comment] 2019-02-03 16:38
Try restarting your machine. Cause the error states that the DB is already in use. So thats only option left. As a DB in use cannot be set as not used by the bot.

**Comment by echthard** [comment] 2019-02-04 11:05
Even after restartig it occurs after a while. 

I have two bots, both pointing to the same configuration name in "Advanced config". Could that be the problem? 

![image](https://user-images.githubusercontent.com/1479483/52204637-0a43a200-2875-11e9-885d-135d58f27d8a.png)


Or what database does it try to connect to?

**Comment by taniman** [comment] 2019-02-04 15:39
2 bots pointing at same config is a problem on it's own. Not this problem though. 
But are these bots running in different folders? 

it really does seem like your bot is trying to access a database in use.  I have not seen this error on my bot's so it is hard to pin point. 
But must be something specific with your machine.

Try 2.2.3 and let me know what happens with that

**Comment by echthard** [comment] 2019-02-04 16:54
Will have to run 2.2.3 for a while to check if the error occurs again. 

Meanwhile, 2.2.3 Is getting incorrect bought_price for EVX that was just bought by a pending order. But even after using the hot config: "EVX_bought_price = 0.0000801" it is not changing the bought price. In the cmd window, it says: 

> 2019-02-04 17:49:53 INFO AverageCalculator - EVX using bought price 0.00008010 for total amount 50.00000000

![image](https://user-images.githubusercontent.com/1479483/52223446-eea4bf80-28a5-11e9-9600-a1dc8595978c.png)

**Comment by echthard** [comment] 2019-02-04 22:33
Still getting errors. This time I've noticed these:

> 2019-02-04 23:29:53 ERROR AppErrorController - org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection

> Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-197]

> Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/echthard/Desktop/BOTJES/botje2/ProfitTrailer/data/ptdb.mv.db [1.4.197/7]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
        at org.h2.mvstore.FileStore.open(FileStore.java:168)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:350)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
        ... 106 more
Caused by: java.nio.channels.OverlappingFileLockException
        at sun.nio.ch.SharedFileLockTable.checkList(Unknown Source)
        at sun.nio.ch.SharedFileLockTable.add(Unknown Source)
        at sun.nio.ch.FileChannelImpl.tryLock(Unknown Source)
        at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
        at java.nio.channels.FileChannel.tryLock(Unknown Source)
        at org.h2.mvstore.FileStore.open(FileStore.java:165)
        ... 109 more

**Comment by taniman** [comment] 2019-02-04 23:31
Still same error.  your database is in use.

Please confirm how you are running your bot.
Do you have any processes auto rebooting the bot in the background.
Do you have any process trying to copy the DB while the bot is running?

AS it stands the problem is clear. But what is causing it on your machine is the question.
So please check your machine for these posibilities. As this is more of a setup issue than a bug.

While the bot is running the database file is locked. This is to avoid corruption of data.
You you not touch the database file or try to move it or open it while the bot is running

**Comment by echthard** [comment] 2019-02-05 12:10
Please confirm how you are running your bot. Yes
Do you have any processes auto rebooting the bot in the background. No
Do you have any process trying to copy the DB while the bot is running? No

Nothing is touching the file as far as I know. Maybe Windows Defender? But it's weird that it is working for a while, every time when I close the cmd window and start the bot again.

Also there are really annoying bought_price issues with 2.2.3, so I decided to go back to 2.1.27 and the database issues are not returning. 

2.2.2 is still working for two other bots though. For one bot it keeps coming with the same db error. Weird.

**Comment by echthard** [comment] 2019-02-05 13:09
I have some though, but that's an other issue. 

1. I bought via a pending order 50 EVX at 8010 sats. Bot says 6400 sats. 
2. Then I use the hot config telling it is 8010, but the bot ignores
3. Later the bot sells those 50 EVX with loss (but bot thinks a huge profit) at 79xx sats. (Not showing in Sales though)
4. And an other pending order buys 50 EVX at 7810 sats and the bot says 8010 sats. (which is prolly from a previous price or previous hot config value)

**Comment by taniman** [comment] 2019-02-05 13:22
Sorry, but I cannot cater the bot for everybody.

If those pending orders were set by the bot and it's now giving incorrect data. I can work with that. But if those pending orders were set on the exchange and are now bought.  The bot tries to fill in the blanks. 

You can send me your database file and the log file in discord and some screenshots I can have a look in the tradehistory of the bot see what I see.

**Comment by RobinopdeBeek** [comment] 2019-02-25 15:54
Getting the same issue. With 2.2.2, 2.2.7 and also with latest 2.2.8. However, I am only using one bot. 

I am also getting the "P13: Timing inconsistency, we are handling it" Error over and over again. Maybe they are related? 

Did anyone else find a fix?

**Comment by taniman** [comment] 2019-02-25 15:58
> Getting the same issue. With 2.2.2, 2.2.7 and also with latest 2.2.8. However, I am only using one bot.
> 
> I am also getting the "P13: Timing inconsistency, we are handling it" Error over and over again. Maybe they are related?
> 
> Did anyone else find a fix?

Please contact support on discord and provide your log file. This error can happen because of various reasons.  That's also why I am closing this ticket now. 

I can be caused my memory problems and connection problems and file access permissions. And seeing as it is system related it needs to be checked by support as I call it not a bug but a setup problem

**Closed by taniman** 2019-02-25 15:58 UTC
