### ISSUE TITLE
StochRSI bug

### ISSUE THREAD

**Issue by Shinisaru** [taniman/profit-trailer#1715] opened 2018-04-29 23:31 UTC
StochRSI indicator is not calculated correctly apparently if value is high for more than number of candles specified in indicators properties.
Here are screenshots to help debugging the problem.
<img width="923" alt="screen shot 2018-04-30 at 01 26 13" src="https://user-images.githubusercontent.com/1769437/39412030-e51706a2-4c15-11e8-866c-ff09741bd817.png">
<img width="1362" alt="screen shot 2018-04-30 at 01 26 33" src="https://user-images.githubusercontent.com/1769437/39412031-e5334880-4c15-11e8-9168-3d82a5dcf0d1.png">

**Comment by SgtBatten** [comment] 2018-04-30 01:51
Duplicate of #1644

**Closed by SgtBatten** 2018-04-30 01:51 UTC
