### ISSUE TITLE
PT2 missing sale

### ISSUE THREAD

**Issue by Fransenson** [taniman/profit-trailer#1781] opened 2018-05-04 09:30 UTC
PT Notifications pushed a sale, it is there on binance and the coin went out of my pairs log. Never appeared in the sales log though. 

Will PT2 eventually get the data from binance or will I have to add it manually to the json?

**Comment by SgtBatten** [comment] 2018-05-04 09:33
Duplicate of #1720

**Closed by SgtBatten** 2018-05-04 09:33 UTC
