### ISSUE TITLE
v2.0.3  STOCHRSI has bug

### ISSUE THREAD

**Issue by g001613001** [taniman/profit-trailer#1804] opened 2018-05-07 23:02 UTC
![image](https://user-images.githubusercontent.com/18544298/39728708-ebb6c76a-528a-11e8-8b7e-ae86dfd068ef.png)
![image](https://user-images.githubusercontent.com/18544298/39728712-ef9fee92-528a-11e8-9d90-a732d3b4c4f3.png)

My indicator set:
RSI_candle_period = 900
RSI_length = 14

**Comment by SgtBatten** [comment] 2018-05-07 23:53
Duplicate of #1611

**Closed by SgtBatten** 2018-05-07 23:53 UTC
