### ISSUE TITLE
Bug with pair_min_listed_days

### ISSUE THREAD

**Issue by mikdesign02** [taniman/profit-trailer#1629] opened 2018-04-24 08:47 UTC
Hi,
I think there is a bug with "pair_min_listed_days"  sometimes my possible buy shows TOO NEW as you can see in the picture in attache. I'm oblige to reload the pm2 for the bot to start trailing.
my pair_min_listed_days = 90
Can you help me.
![image](https://user-images.githubusercontent.com/34874555/39176107-7deb2a90-479b-11e8-80cf-e22e861fe48b.png)

**Comment by SgtBatten** [comment] 2018-04-24 10:27
Duplicate of #1586

**Closed by SgtBatten** 2018-04-24 10:27 UTC
Labels: duplicate
