### ISSUE TITLE
getbalances was throttled. try again in 60

### ISSUE THREAD

**Issue by kj3407** [taniman/profit-trailer#1659] opened 2018-04-26 03:13 UTC
I keep getting this on V2.0 and now I'm starting to get on v 1, what is going on?  Not sure what to do, I have been trying, over an over to go over what maybe something I did, I redid the total set up on V2.0 and it still does it, in fact, it's worst, now it does not even read my balance at all. So I stop running it and just run V1 and it does it but will go back to normal, but it does keep doing it every so often, V1 never did it before.  I am waiting because you said your working on it, but things are just not working on my end.  It's bad because I see online that every body else is working fine, I sure you can see my frustration, please send relief.

**Comment by SgtBatten** [comment] 2018-04-26 04:06
you have not even mentioned what exchange you are on.

**Comment by kj3407** [comment] 2018-04-26 19:26
Bittrex

**Comment by kj3407** [comment] 2018-04-26 20:58
That's what I am getting also, same thing for the last week, V1 does clear out most of the time, V2 never, it started working fine then it just went retarted.

**Comment by Richo005** [comment] 2018-04-27 11:38
Having the sama issue

**Comment by NOP-Commander** [comment] 2018-04-27 11:51
It's getting worse today and the day is not over. Trading works though.

$ grep "2018-04-27.*throttled" ProfitTrailer.log | wc -l
173

I'm not sure how many requests PTFeeder generates against Bittrex but is it possible that the sum of requests from PTFeeder plus ProfitTrailer, both hosted on a single IP, against Bittrex violates any API or Web Request limits? If that could be a reason then ProfitTrailer users not running  PTFeeder should encounter less/no throttling issues on Bittrex. Just a thought.

**Comment by SgtBatten** [comment] 2018-04-27 11:52
Bittrex API rules changed. As stated we have to rewrite the API calls completely for bittrex.

**Comment by NOP-Commander** [comment] 2018-04-27 11:53
Ah sorry, I missed that statement of yours. Thanks for clarification.

**Comment by strahd1778** [comment] 2018-04-29 16:46
Same issue.

**Comment by mack009009** [comment] 2018-05-02 19:31
me too same issue in BITTREX. Please fix api

**Comment by kj3407** [comment] 2018-05-03 01:04
now, neither, v1 or v2 are trading even though v1 is not error-ing as much as v2, but it's not trading on any of my settings right now, I miss 8 trades today only.  This sucks, WHY CAN'T I JUST SWITCH FOR GOD SAKE!!!!!!!!

**Comment by kj3407** [comment] 2018-05-03 02:49
Thank SgtBatten, no hard feelings , just a little crazy, I know you guys are working hard, I guess I am more mad at Bittrex then you guys.  I'm good until then, keep me posted.

**Comment by SgtBatten** [comment] 2018-05-06 21:40
Duplicate of #1593

**Closed by SgtBatten** 2018-05-06 21:40 UTC
