### ISSUE TITLE
STOCH RSI

### ISSUE THREAD

**Issue by n0ts0subtle** [taniman/profit-trailer#1710] opened 2018-04-29 16:31 UTC
Please update the Stoch RSI PT measurments to reflect accurately on the exchange. The old school method may be .2 - .8 but now 20.00 to 80.00 is used. Its confusing.

**Comment by SgtBatten** [comment] 2018-04-30 01:52
Duplicate of #1644

Feature requests can go.on he enhancements repository please

**Closed by SgtBatten** 2018-04-30 01:52 UTC
