### ISSUE TITLE
DCA tables not loading

### ISSUE THREAD

**Issue by CryptoDean** [taniman/profit-trailer#1623] opened 2018-04-24 00:39 UTC
Despite, reinstalling windows and setting up again, trying different computers, I have been frustrated that this problem is not resolved.

Ver 2 Loads fine, Well it does not open I have to go to localhost, then when I go to DCA window in GUI there is no information apart from it telling me I have 2 Coins in DCA, but it does not show them.
I have gone on the chat, I have changed browsers, deleted Cache, changed computers, tried different ports, No error signs and has heartbeats, But get an error message on the page - datatables warning: tables id=dtdcalogs = cannot reinitialize  DataTable and then I get the red message
"there was an error while processing the data received from profit trailer. please give some love, make a coffee and it will be good soon.
well 2 days of coffee and trying to get support, I got no more love and now shaking with 2 days worth of coffee.
please, someone, help sort this issue. yes I have also replaced the Jar file and that does not change anything, I have had to go back to version 1

**Comment by jmarcott86** [comment] 2018-04-24 03:53
I ran into this same problem just now. Turns out I commented out my DEFAULT_DCA_trailing_buy line by mistake.

**Comment by SgtBatten** [comment] 2018-04-24 11:00
Web browser opening automatically is configurable. You might have it disabled.

I agree you should check parameters.

Duplicate of #1562

**Closed by SgtBatten** 2018-04-24 11:00 UTC

**Comment by dmuzizian** [comment] 2018-04-24 14:27
same here
![screenshot_1](https://user-images.githubusercontent.com/15715474/39193600-25ca5dac-4806-11e8-99b8-e1d14c109931.png)

i'm not found solution for this problem :(
