### ISSUE TITLE
STOCH and STOCHRSI still not working in 2.0.1?

### ISSUE THREAD

**Issue by Ghostdoge** [taniman/profit-trailer#1658] opened 2018-04-26 01:16 UTC
I setup the following for STOCH in Pairs.
DEFAULT_A_buy_value = 10

I get readings of zero on all coins in bot.

I also tried the following for STOCHRSI in pairs.
DEFAULT_A_buy_value = 0.1 , which I think is the value of 10 that I'm trying to use.
The readings on bot are very different to trading view still. I believe the value is the K value on Tradingview StochRSI.

Is it possible to just code the bot to accept a single value for K or D for the StochRSI?

**Comment by SgtBatten** [comment] 2018-04-26 04:07
please share screenshot of indicators file

**Comment by sas7085** [comment] 2018-04-26 04:55
In my case  STOCHRSI is 000000  for maximum Pairs. Here is the screen shot. The Trading view is having the Non Zero value . This is for PT 2.0.1 version.  Shared the Trading View screenshot for STEEMBTC - Binance
 
![image](https://user-images.githubusercontent.com/36013435/39286447-07a16a0a-48ec-11e8-85c1-703fcd7a7d44.png)
![image](https://user-images.githubusercontent.com/36013435/39286452-0c9c2cc0-48ec-11e8-9fa9-5ab3d91f4281.png)
![image](https://user-images.githubusercontent.com/36013435/39286456-112c9a04-48ec-11e8-8633-1f324d97f9a3.png)

**Comment by SgtBatten** [comment] 2018-04-26 06:17
Please share buy settings

**Comment by sas7085** [comment] 2018-04-26 13:31
Buy Settings 

> DEFAULT_A_buy_strategy = LOWBB
DEFAULT_A_buy_value = 15
DEFAULT_A_buy_value_limit = -20

> DEFAULT_B_buy_strategy = MACD
DEFAULT_B_buy_value = -0.00000001
DEFAULT_B_buy_value_limit = 0

> DEFAULT_D_buy_strategy = RSI
DEFAULT_D_buy_value = 50
DEFAULT_D_buy_value_limit = 0

> DEFAULT_E_buy_strategy = STOCHRSI
DEFAULT_E_buy_value = 0.20
DEFAULT_E_buy_value_limit = 0

**Comment by HomeY** [comment] 2018-04-26 19:11
I can confirm that 2.0.1 unfortunately doesn't fix the StochRSI value.

![image](https://user-images.githubusercontent.com/1996332/39326681-15fb2578-4996-11e8-806b-76471eed0e56.png)

ETH:
![image](https://user-images.githubusercontent.com/1996332/39326711-2c0202ce-4996-11e8-8b99-14ac57158de1.png)

ICX:
![image](https://user-images.githubusercontent.com/1996332/39326742-407a10ca-4996-11e8-998f-32da192c382d.png)

AION:
![image](https://user-images.githubusercontent.com/1996332/39326767-511539fa-4996-11e8-9b86-8e16528759a1.png)

#BUY SETTINGS#
DEFAULT_A_buy_strategy = STOCHRSI
DEFAULT_A_buy_value = 0.125
DEFAULT_A_buy_value_limit = 0
DEFAULT_B_buy_strategy = EMASPREAD
DEFAULT_B_buy_value = -0.75
DEFAULT_B_buy_value_limit = -5
DEFAULT_C_buy_strategy = MACD
DEFAULT_C_buy_value = -0.000000001

**Comment by ricardodacosta** [comment] 2018-04-26 21:52
Chance buy_value_limit to a number other than 0 and give it a try.

**Comment by Ghostdoge** [comment] 2018-04-27 03:07
Mine seems to be working fine now. I just saw in another post that PT doesn't read buy/sells, and rather order book. So that's why TV and PT are seeing different values. 

Not sure if that's the best option, as spoofing order books is pretty regular I think. Anyway here is a screen of my working settings for a value of 10 for STOCHRSI.

https://puu.sh/AbbHV/71878b9d5a.png

**Comment by HomeY** [comment] 2018-04-27 18:50
@ricardodacosta why would changing the limit affect the StochRSI values? If definitely shouldn't, and according to the Wiki, 0 simply disables the limit. Still i tested it, and luckily i was right, it doesn't change the values at all.

@Ghostdoge good point on the buys/sells & orderbook differences, but that can't explain a difference of at least 25 points with pairs that only have a few Sats spread on the exchange. I would expect an error margin of 2-4% depending on the spread

**Comment by yohgii** [comment] 2018-04-27 19:55
I am having the same issue. The stochrsi was actually working when I first set up PT2.0. Now it doesn't. All of the BSV in the possible buy log are all at 0.0.

**Comment by HomeY** [comment] 2018-04-27 19:59
@yohgii it might have looked better, but also those values were (far from) correct.

I'm just trying to wrap my head around the reason why we have such a big difference with the TV values.... But then again, i have no clue what formula is used to calculate both STOCH and StochRSI.

**Comment by yohgii** [comment] 2018-04-27 20:10
I figured out the error with mine
I dont know if it is the same for you guys, but, I also use pt feeder. the stoch rsi candle period was not there. and was replaced incorrectly with stoch length. Once I correct the indicators my pt is matching tradingview. Hopefully it is the same for your guys.

**Comment by SgtBatten** [comment] 2018-04-27 20:14
Stochrsi does not match TV as we have no way currently to read or use the K and D values.

Stoch should be working

**Comment by HomeY** [comment] 2018-04-27 20:17
So what about adding 2 variables in the INDICATORS.properties file, like:
StochRSI_K = 3 (default)
StochRSI_D = 3 (default)
so these can be used in the formule, so we get closer to the TV calculation?

**Comment by SgtBatten** [comment] 2018-04-27 20:31
It's an issue of getting the data from binance. 

If STOCH doesn't work with binance please raise a seperate issue.

**Comment by SgtBatten** [comment] 2018-04-30 01:51
Duplicate of #1644

**Closed by SgtBatten** 2018-04-30 01:51 UTC
