### ISSUE TITLE
DCA not working Ver: 1.2.6.18

### ISSUE THREAD

**Issue by GLock-PPC** [taniman/profit-trailer#1161] opened 2018-02-19 07:58 UTC
Keep getting the following error also on pairs with over 1000 BTC Volume. No restriction on volume for DCA set, so it should not happen.
`There is not enough volume to make a successfull DCA`

**Comment by Icantknowhow** [comment] 2018-02-19 08:37
My DCA is not working either however I am not getting any error message, just no DCA capabitity

**Comment by dorjedan** [comment] 2018-02-19 08:47
I am also seeing, "There is not enough volume to make a successful DCA". Also have no restriction on volume for DCA set.

**Comment by orty87** [comment] 2018-02-19 10:28
I also have dca problems since v17. Some pairs work but some don't. Because my bot was off for a day I have 3 pairs with around - 20%. All of them are at trigger 3 which is set at - 10. So normally it should do a instant buy when I turn the bot on but they are just trailing all the time. Trailing buy is set at 0.3.

**Comment by Galenki** [comment] 2018-02-19 13:13
adding buy_available_volume_trigger = 150 in dca.properties can fix your issue maybe?

**Comment by YoJeff** [comment] 2018-02-19 15:54
Please use support.   This is not a bug, it's your settings.

**Comment by znafca** [comment] 2018-02-19 17:16
its not settings, I confirm I do have same issues since couple of hours (for almost 1 day all was ok)

**Comment by znafca** [comment] 2018-02-19 20:29
update from my side: at the same time when I saw all that messages in the pt log, the binance web page had very bad response (it did not process my requests most of the time, to see my orders I had to refresh the page couple of times for example). Now, when I can do manual work on the exchange with no issues the bot is not complaining on volume anymore. Do you guys think that the issue is that bot is not handling such exchange problems?
I also saw that volume in the bot GUI was 0 for all the pairs I had that time, now I see correct volume.

**Comment by runner989** [comment] 2018-02-19 20:37
I am starting to think that the error being thrown is a bogus error/false alarm being thrown at the wrong times; which would point to a problem in error handling code.

The reason I say this is because I was getting this error in my logs (XXXXXX is my own change):
2018-02-19 15:19 -05:00: 2018-02-19 15:19:34 INFO ProfitTrailerService - SOM is active for XXXXXX -- Manually set in PAIRS.properties
2018-02-19 15:19 -05:00: 2018-02-19 15:19:59 INFO DCAStrategyRunner - There is not enough volume to make a successfull DCA XXXXXX

I changed my DCA to ignore SOM and it DCA'd successfully and without throwing the volume error.

**Comment by znafca** [comment] 2018-02-19 20:41
runner989 are you using binance? can you restore the SOM config and try again now?

**Comment by orty87** [comment] 2018-02-19 20:48
My max cost was set at 0.1, after changing it to 0 dca was working again. I still don't understand why because all the buys were below 0.1 btc.

**Comment by znafca** [comment] 2018-02-19 22:05
next update: if I use VPN and "move" myself out of Poland all seems to be working fine, no 0 volume, no freeze in the GUI

**Comment by taniman** [comment] 2018-02-19 22:12
seems ypu don't understand the error message @GLock-PPC. It's not talking about volume. it's talking about orderbook availability

**Comment by znafca** [comment] 2018-02-19 22:27
sorry, maybe I simply shall not comment here and open another case. What I want to say is that I did see the "There is not enough volume to make a successfull DCA", multiple times, for all the pairs in the DCA. Then I realized that all my pairs in DCA shows 0 for volume. I stopped the bot, logged in to binance with my browser and realized that binance works very slow and does not always show what I want to display (like filtering on historical orders for example was working for a sec, then another attempt was never finished with success, then again ok, ...). Another start of the bot, all seems to work, couple of minutes later freeze in the bot GUI (was able to click on left menu objects but there was no change in the main window content) - checking binance at the same time in the browser and again issues with that. I asked my friends outside of Poland to check at that moment if they have no issue with binance - answer was no, works like a charm. Started the VPN and connected to Germany server, started the bot, so far no issues.

**Comment by runner989** [comment] 2018-02-19 22:47
@znafca  I am on Binance.  The SOM was activated just on that one pair.  I enabled it again on another pair before it could DCA and yes, the message appears again directly after the INFO - SOM is active for XXXXXX.

**Comment by runner989** [comment] 2018-02-19 23:49
@taniman At first I did not understand the error message because it seemed be showing up after any error message, from SOM active for a pair to additional DCA levels not defined.  Adding the buy_available_volume_trigger setting in the DCA.properties made the error quit appearing.  Without that entry I am still getting that notification.  Is this a required configuration line item now?

**Comment by taniman** [comment] 2018-02-20 14:56
addind this line 'buy_available_volume_trigger' should not make the error disappear. As the error is produced by that setting.

buy_available_volume_trigger = 100 is now a default setting in the bot. even if you don't set it yourself.

**Comment by taniman** [comment] 2018-02-20 14:58
I will close this issue as the original issue reported by issue creator is not an issue. 

buy_available_volume_trigger has a default setting of 100 in the bot. this means it will look in the order book and only buy a pair if there is enough coin being sold in the order book to buy at the price we want

**Closed by taniman** 2018-02-20 14:58 UTC
Labels: core, needs verification

**Comment by GLock-PPC** [comment] 2018-02-21 02:33
Would be useful to introduce these kind of details in the wiki for more transparency and better understanding and to avoid issues reporting where not needed.
