### ISSUE TITLE
Wrong average buy price

### ISSUE THREAD

**Issue by jcfii** [taniman/profit-trailer#1858] opened 2018-05-14 13:24 UTC
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jcfii** [comment] 2018-05-14 13:26
Bought STRAT one time at .0007230 shows as 0.00073424  Hot config doesn't change anything

**Comment by SgtBatten** [comment] 2018-05-14 20:17
Duplicate of #1859

**Comment by SgtBatten** [comment] 2018-05-14 20:17
I know this was earlier but they filled out the template correctly

**Closed by SgtBatten** 2018-05-14 20:17 UTC
