### ISSUE TITLE
V2 brings backs old issue - DCA sells at loss/wrong bought price when multiple sells

### ISSUE THREAD

**Issue by yunier2002** [taniman/profit-trailer#1713] opened 2018-04-29 20:06 UTC
Old issue ticket: https://github.com/taniman/profit-trailer/issues/777

I'm seeing the same issues in this version 2.0 I've seen in the past where when PT sells in multiple sells (especially on big total amounts) at an incorrect bought price, showing inflated profits and sometimes based on correct bought price it really is selling at a loss.

Here is a screenshot of a sales example today.

<img width="1352" alt="screenshot 2018-04-29 16 03 51" src="https://user-images.githubusercontent.com/35727467/39410497-3465bad6-4bc7-11e8-9b0b-0ead8880e170.png">

**Comment by SgtBatten** [comment] 2018-04-29 20:33
Duplicate of #1705

**Closed** 2018-04-29 22:12 UTC
