### ISSUE TITLE
DCA partial sell loses bought price

### ISSUE THREAD

**Issue by leoneparise** [taniman/profit-trailer#1708] opened 2018-04-29 12:59 UTC
Some of my DCAs need more than 1 sell order to be cleared but the bot is loosing the bought price after some sells. I'm started to experience this issue after I upgrade to PT 2.0. It's happening quite a lot, when the bot loses the bought price it can't sell, leaving good opportunities behind and worse, when the coin is on DCA. I need to set the price manually using hot config to get the profit.

Here is an examples of what's going on:
<img width="1386" alt="screen shot 2018-04-30 at 18 08 15" src="https://user-images.githubusercontent.com/1442927/39440106-c99f45ec-4ca1-11e8-934a-990b83abb175.png">

**Comment by Rawhound** [comment] 2018-04-30 12:44
I wanted to add I'm also having this problem for the last couple of days DCA sales.

**Comment by Rawhound** [comment] 2018-04-30 13:46
My bot has just had this happen again.  It has just occured after performing a DCA BUY, after completing some partial DCA SELLs orders.

**Comment by SgtBatten** [comment] 2018-05-02 11:16
Duplicate of #1725

**Closed by SgtBatten** 2018-05-02 11:16 UTC
